python main.py --obj_name cracker_box --scene_id 0
python main.py --obj_name tomato_soup_can --scene_id 1
python main.py --obj_name sugar_box --scene_id 2
python main.py --obj_name mustard_bottle --scene_id 3
python main.py --obj_name potted_meat_can --scene_id 4
python main.py --obj_name banana --scene_id 5
python main.py --obj_name bowl --scene_id 6
python main.py --obj_name mug --scene_id 7
python main.py --obj_name power_drill --scene_id 8
python main.py --obj_name scissors --scene_id 9
python main.py --obj_name chips_can --scene_id 10
python main.py --obj_name strawberry --scene_id 11
python main.py --obj_name apple --scene_id 12
python main.py --obj_name lemon --scene_id 13
python main.py --obj_name peach --scene_id 14
python main.py --obj_name pear --scene_id 15
python main.py --obj_name orange --scene_id 16
python main.py --obj_name plum --scene_id 17
python main.py --obj_name knife --scene_id 18
python main.py --obj_name phillips_screwdriver --scene_id 19
python main.py --obj_name flat_screwdriver --scene_id 20
python main.py --obj_name racquetball --scene_id 21
python main.py --obj_name b_cups --scene_id 22
python main.py --obj_name d_cups --scene_id 23
python main.py --obj_name a_toy_airplane --scene_id 24
python main.py --obj_name c_toy_airplane --scene_id 25
python main.py --obj_name d_toy_airplane --scene_id 26
python main.py --obj_name f_toy_airplane --scene_id 27
python main.py --obj_name h_toy_airplane --scene_id 28
python main.py --obj_name i_toy_airplane --scene_id 29
python main.py --obj_name j_toy_airplane --scene_id 30
python main.py --obj_name k_toy_airplane --scene_id 31
python main.py --obj_name padlock --scene_id 32
python main.py --obj_name dragon --scene_id 33
python main.py --obj_name secret_repair --scene_id 34
python main.py --obj_name jvr_cleaning_foam --scene_id 35
python main.py --obj_name dabao_wash_soup --scene_id 36
python main.py --obj_name nzskincare_mouth_rinse --scene_id 37
python main.py --obj_name dabao_sod --scene_id 38
python main.py --obj_name soap_box --scene_id 39
python main.py --obj_name kispa_cleanser --scene_id 40
python main.py --obj_name darlie_toothpaste --scene_id 41
python main.py --obj_name nivea_men_oil_control --scene_id 42
python main.py --obj_name baoke_marker --scene_id 43
python main.py --obj_name hosjam --scene_id 44
python main.py --obj_name pitcher_cap --scene_id 45
python main.py --obj_name dish --scene_id 46
python main.py --obj_name white_mouse --scene_id 47
python main.py --obj_name camel --scene_id 48
python main.py --obj_name deer --scene_id 49
python main.py --obj_name zebra --scene_id 50
python main.py --obj_name large_elephant --scene_id 51
python main.py --obj_name rhinocero --scene_id 52
python main.py --obj_name small_elephant --scene_id 53
python main.py --obj_name monkey --scene_id 54
python main.py --obj_name giraffe --scene_id 55
python main.py --obj_name gorilla --scene_id 56
python main.py --obj_name weiquan --scene_id 57
python main.py --obj_name darlie_box --scene_id 58
python main.py --obj_name soap --scene_id 59
python main.py --obj_name black_mouse --scene_id 60
python main.py --obj_name dabao_facewash --scene_id 61
python main.py --obj_name pantene --scene_id 62
python main.py --obj_name head_shoulders_supreme --scene_id 63
python main.py --obj_name thera_med --scene_id 64
python main.py --obj_name dove --scene_id 65
python main.py --obj_name head_shoulders_care --scene_id 66
python main.py --obj_name lion --scene_id 67
python main.py --obj_name coconut_juice_box --scene_id 68
python main.py --obj_name hippo --scene_id 69
python main.py --obj_name tape --scene_id 70
python main.py --obj_name rubiks_cube --scene_id 71
python main.py --obj_name peeler_cover --scene_id 72
python main.py --obj_name peeler --scene_id 73
python main.py --obj_name ice_cube_mould --scene_id 74
python main.py --obj_name bar_clamp --scene_id 75
python main.py --obj_name climbing_hold --scene_id 76
python main.py --obj_name endstop_holder --scene_id 77
python main.py --obj_name gearbox --scene_id 78
python main.py --obj_name mount1 --scene_id 79
python main.py --obj_name mount2 --scene_id 80
python main.py --obj_name nozzle --scene_id 81
python main.py --obj_name part1 --scene_id 82
python main.py --obj_name part3 --scene_id 83
python main.py --obj_name pawn --scene_id 84
python main.py --obj_name pipe_connector --scene_id 85
python main.py --obj_name turbine_housing --scene_id 86
python main.py --obj_name vase --scene_id 87
